### ISSUE TITLE
not unpack

### ISSUE THREAD

**Issue by kowtham2002** [ribthegreat99OrN0P/Agile.NET-Deobfuscator-Latest#4]
resolving assemblies from framework version : 4.5
started Call Resolver
started String Decryption
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at Agile.NET_Deobfuscator_Updated.Modules.Strings.FindData(ModuleDefinition def) in D:\Visual Studio Projects\AgileDeobfuscators\Agile.NET-Deobfuscator-Updated\Agile.NET-Deobfuscator-Updated\Agile.NET-Deobfuscator-Updated\Modules\Strings.cs:line 52
   at Agile.NET_Deobfuscator_Updated.Modules.Strings.Process(Context context) in D:\Visual Studio Projects\AgileDeobfuscators\Agile.NET-Deobfuscator-Updated\Agile.NET-Deobfuscator-Updated\Agile.NET-Deobfuscator-Updated\Modules\Strings.cs:line 23
   at Agile.NET_Deobfuscator_Updated.Program.Main(String[] file) in D:\Visual Studio Projects\AgileDeobfuscators\Agile.NET-Deobfuscator-Updated\Agile.NET-Deobfuscator-Updated\Agile.NET-Deobfuscator-Updated\Program.cs:line 44

**Comment by kowtham2002** [comment]
can unpack this bro 
https://file.io/1MDc9gY9cQf5

**Comment by ribthegreat99OrN0P** [comment]
File is deleted https://www.file.io/deleted/

**Comment by kowtham2002** [comment]
HII NEW FILE LINK 
https://www.dropbox.com/s/9ds2775f7x15uk9/UNPACK%20ME.exe?dl=0

**Comment by kowtham2002** [comment]
> File is deleted https://www.file.io/deleted/

HII NEW FILE LINK
https://www.dropbox.com/s/9ds2775f7x15uk9/UNPACK%20ME.exe?dl=0

**Comment by ribthegreat99OrN0P** [comment]
issue fixed in latest commit. Please redownload the source or redownload compiled binaries
